Repository gsanders5/Group_5, pull requests merged in 2022-10, with the labels that each got.

#46 Profile/Auth Pages - Resolves #19, #45, #43, #42, #41
  Django/Django/settings.py
  Django/Django/urls.py
  Django/SocialSite/forms.py
  Django/SocialSite/migrations/0003_alter_account_first_name_alter_account_last_name.py
  Django/SocialSite/models.py
  Django/SocialSite/templates/SocialSite/Account/account.html
  Django/SocialSite/templates/SocialSite/Account/edit_account.html
  Django/SocialSite/templates/SocialSite/Account/search_results.html
  Django/SocialSite/templates/SocialSite/PasswordChange/password_change.html
  Django/SocialSite/templates/SocialSite/login.html
  Django/SocialSite/templates/SocialSite/register.html
  Django/SocialSite/views.py
  Django/templates/snippets/base_css.html
  Django/templates/snippets/header.html
  Django/templates/testbase.html
Labels: backend, frontend, database

#49 Add CI intigration #48
  README.md
Labels: documentation, enhancement

#50 Friend System with Views Resolves #35, #33
  Django/Django/urls.py
  Django/SocialSite/admin.py
  Django/SocialSite/friend_request_status.py
  Django/SocialSite/migrations/0004_friendrequest.py
  Django/SocialSite/models.py
  Django/SocialSite/templates/SocialSite/Account/account.html
  Django/SocialSite/templates/SocialSite/Account/edit_account.html
  Django/SocialSite/templates/SocialSite/Account/search_results.html
  Django/SocialSite/templates/SocialSite/Friend/accept_friend_request.html
  Django/SocialSite/templates/SocialSite/Friend/friend_requests.html
  Django/SocialSite/templates/SocialSite/Friend/remove_friend.html
  Django/SocialSite/templates/SocialSite/Friend/send_friend_request.html
  Django/SocialSite/templates/SocialSite/login.html
  Django/SocialSite/templates/SocialSite/register.html
  Django/SocialSite/utils.py
  Django/SocialSite/views.py
  Django/personal/templates/personal/home.html
  Django/templates/base.html
  Django/templates/hello.html
  Django/templates/index.html
  Django/templates/snippets/base_css.html
  Django/templates/snippets/header.html
Labels: backend, frontend

#52 Add live demo to README, resolves #51
  README.md
Labels: documentation, enhancement, frontend

#64 Search fix Resolves #63
  Django/SocialSite/views.py
Labels: backend

#65 Update README.md Frontend Component
  README.md
Labels: documentation

#75 Update Profile Page to Prep for Posts/Create Models for Posts & Comments/Initial Backend Start/Comments Started
  Django/Django/settings.py
  Django/Django/urls.py
  Django/SocialSite/migrations/0005_comment_rename_content_post_description_and_more.py
  Django/SocialSite/models.py
  Django/SocialSite/templates/SocialSite/Account/account.html
  Django/SocialSite/templates/SocialSite/Account/edit_account.html
  Django/SocialSite/utils.py
  Django/SocialSite/views.py
  Django/templates/snippets/header.html
Labels: documentation, backend, frontend, database

#80 Post Functionality with Liking and Posting
  .gitignore
  .idea/Group_5.iml
  Django/Django/urls.py
  Django/SocialSite/forms.py
  Django/SocialSite/migrations/0011_rename_description_post_textcontent.py
  Django/SocialSite/migrations/0012_post_is_image.py
  Django/SocialSite/migrations/0013_alter_post_image.py
  Django/SocialSite/migrations/0014_alter_post_textcontent.py
  Django/SocialSite/migrations/0015_alter_post_createdat.py
  Django/SocialSite/migrations/0016_rename_textcontent_post_text_content.py
  Django/SocialSite/migrations/0017_rename_createdat_post_created_at_and_more.py
  Django/SocialSite/migrations/0018_post_is_shared_post_post_shared_post_and_more.py
  Django/SocialSite/migrations/0019_alter_commentlist_comments.py
  Django/SocialSite/migrations/0020_remove_commentlist_comments_commentlist_comments.py
  Django/SocialSite/migrations/0021_post_userswhoshared.py
  Django/SocialSite/migrations/0022_post_poster.py
  Django/SocialSite/models.py
  Django/SocialSite/templates/SocialSite/Account/account.html
  Django/SocialSite/templates/SocialSite/Account/account_like_post_request.html
  Django/SocialSite/templates/SocialSite/Account/account_posts_js.html
  Django/SocialSite/templates/SocialSite/Account/edit_account_js.html
  Django/SocialSite/templates/SocialSite/Friend/send_friend_request.html
  Django/SocialSite/templates/SocialSite/Post/create_post.html
  Django/SocialSite/templates/SocialSite/Post/create_post_js.html
  Django/SocialSite/templates/SocialSite/Post/like_post_request.html
  Django/SocialSite/templates/SocialSite/Post/post.html
  Django/SocialSite/templates/SocialSite/Post/post_js.html
  Django/SocialSite/templates/SocialSite/Post/post_requests.html
  Django/SocialSite/templates/SocialSite/home.html
  Django/SocialSite/utils.py
  Django/SocialSite/views.py
  Django/media/defaultPostImage.jpeg
  Django/media/defaultPostImage.png
  Django/media_cdn/profile_images/1/profile_image.png
  Django/static_cdn/defaultPostImage.jpeg
  Django/static_cdn/defaultPostImage.png
Labels: backend, frontend, database

#81 Home redirect to Login
  Django/SocialSite/views.py
Labels: backend, frontend

#82 Home image changes
  Django/SocialSite/templates/SocialSite/home.html
Labels: backend, frontend, database

#83 Dist folder
  .gitignore
  Django/static/cropperjs/dist/cropper.common.js
  Django/static/cropperjs/dist/cropper.css
  Django/static/cropperjs/dist/cropper.esm.js
  Django/static/cropperjs/dist/cropper.js
  Django/static/cropperjs/dist/cropper.min.css
  Django/static/cropperjs/dist/cropper.min.js
  Django/static_cdn/cropperjs/dist/cropper.common.js
  Django/static_cdn/cropperjs/dist/cropper.css
  Django/static_cdn/cropperjs/dist/cropper.esm.js
  Django/static_cdn/cropperjs/dist/cropper.js
  Django/static_cdn/cropperjs/dist/cropper.min.css
  Django/static_cdn/cropperjs/dist/cropper.min.js
Labels: backend

#85 Account Shared Image Fix
  Django/SocialSite/templates/SocialSite/Account/account.html
Labels: frontend

#86 Account Image Fix 2.0
  Django/SocialSite/templates/SocialSite/Account/account.html
Labels: frontend

#88 Text Post Links
  Django/SocialSite/templates/SocialSite/Account/account.html
  Django/SocialSite/templates/SocialSite/home.html
Labels: frontend
